# Catalogue Management Service Spring Reactive Restful APIs
info:
  app:
    name: Driver Registry Service
    description: A RESTful API for drivers, licenses, and their registrations.
    version: 1.0.0
# Spring boot actuator configurations
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics
# SpringDoc configurations
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
# Spring root configurations
spring:
  jackson:
    date-format: dd-MM-yyyy
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false